name: "ChargeX Frontend"
description: "ChargeX Frontend Project - React + Vite + TypeScript"
version: "1.0.0"

# Project structure configuration
project_path: "."
root_directories:
  - "src"
  - "public"
  - "config"

# File patterns to include/exclude
include_patterns:
  - "**/*.ts"
  - "**/*.tsx"
  - "**/*.js"
  - "**/*.jsx"
  - "**/*.json"
  - "**/*.css"
  - "**/*.html"

exclude_patterns:
  - "node_modules/**"
  - "dist/**"
  - "build/**"
  - ".git/**"
  - "*.d.ts"
  - "coverage/**"

# Language configuration
languages:
  - typescript
  - javascript
  - css
  - json
  - html

# Technology stack
technologies:
  - React 19
  - Vite 7
  - TypeScript 5.8
  - TailwindCSS 4
  - React Router 7
  - TanStack Query 5
  - Ant Design 5

# Development tools
dev_tools:
  - eslint
  - vite

# Analysis settings
analysis:
  depth: "deep"
  include_dependencies: true
  cross_file_analysis: true

# Code style settings
code_style:
  indent: 2
  quote_style: "double"
  semicolons: true

# Semantic retrieval configuration
semantic:
  enabled: true
  index_symbols: true
  index_imports: true
  index_exports: true

# Read-only mode (set to true to prevent modifications)
read_only: false

# Context settings for IDE assistant
context:
  mode: "ide-assistant"
  max_context_files: 10
  include_git_history: false
